<a href="https://colab.research.google.com/github/GECarlo/CodingDojo/blob/main/ECG_Distance_and_time_Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [2]:
import pandas as pd
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [3]:
distance = [100,200,400,800,1500,3000,5000,10000]
distance

[100, 200, 400, 800, 1500, 3000, 5000, 10000]

3) Use the np.min() and np.max() functions to find the minimum and maximum distances

In [4]:
np.min(distance), np.max(distance)

(100, 10000)

4) To find the average distance, use the np.mean() function

In [5]:
np.mean(distance)

2625.0

5) use the np.sum() function to find the total distance

In [6]:
np.sum(distance)

21000

6) Another valuable function is the np.cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [7]:
np.cumsum(distance)

array([  100,   300,   700,  1500,  3000,  6000, 11000, 21000])

7) To round all of the values in an array, use np.round()

In [8]:
np.round(distance)

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [9]:
time = [10.62,21.34,48.25,113.43,233.96,506.53,866.17,1757.45]
time

[10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45]

9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [10]:
speed = np.divide(distance, time)
speed, speed.mean()

(array([9.41619586, 9.37207123, 8.29015544, 7.0528079 , 6.41135237,
        5.92265019, 5.77253888, 5.69006231]), 7.240979270608744)

10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [1]:
# cheetah speed in m/s

# convert miles to meters (1mi = 1609.34m)
75 * 1609.34 # = 120700.5m/hr

120700.5

In [12]:
# convert 120700.5m to minutes
120700.5 / 60 # = 2011.675 m/min

2011.675

In [13]:
# convert 2011.675 to seconds
cheetah_ave_speed = 2011.675 / 60 # = 33.52m/s
cheetah_ave_speed

33.52791666666666

In [14]:
# the mean of the athletes speed is 7.24m/s
athlete_ave_speed = np.mean(speed)
athlete_ave_speed

7.240979270608744

In [15]:
# therefore the average speed of a cheetah is 3.63x or 363% faster than the average athlete
comparison = cheetah_ave_speed / athlete_ave_speed - 1
comparison

3.6303014293601192